### ISSUE TITLE
pre-processed graphs and super-patch graph construction

### ISSUE THREAD

**Issue by hongdavid94** [ruitian-olivia/IGI-DL#1]
Hello, thank you for making this package. I have realized any of the files mentioned in the README are not in the git anymore (e.g. ./preprocessed_data)

I have attempted to preprocess the H&E images myself but I am stuck in the 1.3 step of nuclei segmentation step. It is not clear to me how IGI-DL leveraged hovernet to complete this task. I suspect that you had to devise your own code block within hovernet to complete this task.

Could you share the hovernet code used to generate the graphs or the preprocessed graphs themselves? I would like to understand this process so that I could convert my own H&E images into the graphs and test your package.

Thank you !

**Comment by ruitian-olivia** [comment]
Hi, we used the HoverNet code in [https://github.com/simongraham/hovernet_inference](https://github.com/simongraham/hovernet_inference) to conduct nuclei segmentation  for HE-stained images in the step 1.3. Based on the output of step 1.3, you can run the code in step 1.4, 1.5, 1.6, 1.7 to preprocess features of segmented nuclei. Then, in the step 3 (**Nuclei-Graphs construction**), you can finally generate the graphs based HE-stained images. Thank you.

**Comment by hongdavid94** [comment]
Yes thank you, I was able to resolve the issue in hovernet_inference. It is currently using deprecated and outdated versions of tensorpack and tensorflow relative to python3.9 (mentioned as major dependency in your readme.txt).

Are you planning to share the ./preprocessed_data in your repository?

**Comment by ruitian-olivia** [comment]
The size of ./preprocessed_data is very large, and GitHub cannot store such a large amount of data. Our IGI-DL model runs on Python 3.9. The HoverNet part in preprocessing needs to be reconfigured according to the description in the hovernet_inference repository. We used Python 3.6 to run HoverNet. We suggest you try again so that you can apply the entire preprocessing process to your own in-house dataset.

**Comment by hongdavid94** [comment]
yes I am going through the steps right now... thank you so much! I suspect that other people who are doing this on their own will face issue using hovernet-inference. they must use a specific tensorflow version 1.X to run it. For my case, I ended up updating hovernet-inference scripts myself to fit my enviornment (tensorflow version 2.X)

**Comment by LittpeLoveLitrin** [comment]
> 是的，我现在正在完成这些步骤......非常感谢！我怀疑其他自己做这件事的人在使用 hovernet 推理时会遇到问题。他们必须使用特定的 TensorFlow 版本 1.X 来运行它。就我而言，我最终自己更新了 hovernet 推理脚本以适应我的环境（tensorflow 版本 2.X）

Sorry to bother you. Could you share your Hovernet code? I encountered the same issue at this step, and the problem persists during the configuration. I'd appreciate your help. Thank you.
